import './globals.css'
import { Inter } from 'next/font/google'
import Link from 'next/link'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const links = [
    { href: '/', label: 'HOME' },
    { href: '/blog', label: 'BLOG' },
    { href: '/about', label: 'ABOUT' },
    { href: '/contact', label: 'CONTACT' },
    { href: '/portfolio', label: 'PORTFOLIO' },
  ]

  return (
    <html lang="en">
      <body className={inter.className}>
        <div className=" text-center"> </div>
        <div className="flex justify-between">
          <ul>
            {links.map(({ href, label }) => (
              <li key={href}>
                <Link href={href}>{label}</Link>
                <a>{label}</a>
              </li>
            ))}
          </ul>
        </div>

        <div>{children}</div>
      </body>
    </html>
  )
}
