import './globals.css'
import { Inter } from 'next/font/google'
import Link from 'next/link'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className} >
        <div className=' text-center'> SECTION BAR LAYOUT HERE?</div>
        <div className="flex justify-between">
          
          <Link href= '/blog'> BLOG </Link>
          <Link href="/about" >ABOUT</Link >
          <Link href="/contact">CONTACT</Link >
          <Link href= "/portfolio">PORTFOLIO</Link >
        </div>
   
        <div>{children}</div>

      
      
      </body>
    </html>
  )
}
